<?php

//echo $_SERVER['PHP_SELF'];

// echo $_SERVER['GATEWAY_INTERFACE'];

//ECHO $_SERVER['SERVER_ADDR']
//ECHO $_SERVER['SERVER_NAME'];
//ECHO $_SERVER['SERVER_SOFTWARE'];
//ECHO $_SERVER['SERVER_PROTOCOL'];
//ECHO $_SERVER['SERVER_METHOD'];
//ECHO $_SERVER['RQUEST_TIME'];
// $_SERVER['QUERY_STRING'];
//ECHO $_SERVER['HTTP_ACCEPT'];
// ECHO $_SERVER['HTTP_ACCEPT_CHARSET'];
//ECHO $_SERVER['HTTP_HOST'];
//ECHO $_SERVER['HTTP_REFERER'];
ECHO $_SERVER['HTTPS'];

?>